version: '3.3'

services:
  postgres-db:
    image: postgres:12.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_DB: app-db
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8181:8000"
    depends_on:
      - postgres-db